{"uuid": "016b30df-5fa4-4158-a955-b9c86c7bf4bb", "children": ["e435a0d4-89d3-43a8-84d6-0e79e692d740"], "befores": [{"name": "test_login", "status": "failed", "statusDetails": {"message": "AssertionError: assert False\n", "trace": "  File \"/usr/local/lib/python3.7/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/usr/local/lib/python3.7/site-packages/_pytest/fixtures.py\", line 937, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/usr/local/lib/python3.7/site-packages/_pytest/fixtures.py\", line 794, in call_fixture_func\n    res = fixturefunc(**kwargs)\n  File \"/scipt/python/testerhome_pratice/pytest_homework/conftest.py\", line 23, in test_login\n    assert False\n"}, "start": 1558231061347, "stop": 1558231061347}], "start": 1558231061347, "stop": 1558231061410}