{"uuid": "89c7548b-961d-4376-83a5-ea4a73d2c0fb", "children": ["ba87cea6-11ad-428b-b9f9-40e2030a4080"], "befores": [{"name": "test_login", "status": "failed", "statusDetails": {"message": "AssertionError: assert False\n", "trace": "  File \"/usr/local/lib/python3.7/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/usr/local/lib/python3.7/site-packages/_pytest/fixtures.py\", line 937, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/usr/local/lib/python3.7/site-packages/_pytest/fixtures.py\", line 794, in call_fixture_func\n    res = fixturefunc(**kwargs)\n  File \"/scipt/python/testerhome_pratice/pytest_homework/conftest.py\", line 23, in test_login\n    assert False\n"}, "start": 1557803809147, "stop": 1557803809147}], "start": 1557803809147, "stop": 1557803809152}