{"uuid": "e46cddb6-c8ea-460c-9239-a10494435ecd", "children": ["2de6925a-dac8-498e-a589-5e5537caf69d"], "befores": [{"name": "test_login", "status": "failed", "statusDetails": {"message": "AssertionError: assert False\n", "trace": "  File \"/usr/local/lib/python3.7/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/usr/local/lib/python3.7/site-packages/_pytest/fixtures.py\", line 937, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/usr/local/lib/python3.7/site-packages/_pytest/fixtures.py\", line 794, in call_fixture_func\n    res = fixturefunc(**kwargs)\n  File \"/scipt/python/testerhome_pratice/pytest_homework/conftest.py\", line 21, in test_login\n    assert False\n"}, "start": 1557803633638, "stop": 1557803633638}], "start": 1557803633638, "stop": 1557803633643}