{"uuid": "ce3bd44e-e7b3-4b04-a60f-20bc27b2ca25", "children": ["d536660b-8308-4f95-a9ff-402e4bbf1bd9"], "befores": [{"name": "test_login", "status": "failed", "statusDetails": {"message": "AssertionError: assert False\n", "trace": "  File \"/usr/local/lib/python3.7/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/usr/local/lib/python3.7/site-packages/_pytest/fixtures.py\", line 937, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/usr/local/lib/python3.7/site-packages/_pytest/fixtures.py\", line 794, in call_fixture_func\n    res = fixturefunc(**kwargs)\n  File \"/scipt/python/testerhome_pratice/pytest_homework/conftest.py\", line 23, in test_login\n    assert False\n"}, "start": 1558231061414, "stop": 1558231061414}], "start": 1558231061414, "stop": 1558231061423}